yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "eslint-config-airbnb-typescript@*":
    dependencies:
      "eslint-config-airbnb-base": "*"
      "eslint": "*"
      "eslint-plugin-import": "*"
  "eslint-module-utils@*":
    dependencies:
      "eslint-import-resolver-node": "*"
