version: "3.8"

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.client

  redis:
    image: redis:6.2-alpine

  nodejs-app:
    build:
      context: ./
      dockerfile: Dockerfile.server
