version: "3.8"

services:
  nginx:
    build:
      target: nginx-dev
    ports:
      - 8080:80

  nodejs-app:
    build:
      target: dev
    volumes:
      - ./packages/server/src:/home/node/app/src
      - ./packages/server/package.json:/home/node/app/package.json
      - ./packages/server/tsconfig.json:/home/node/app/tsconfig.json
    ports:
      - 5000:5000

  webpack-dev-server:
    build:
      context: ./
      dockerfile: Dockerfile.client
      target: dev
    volumes:
      - ./packages/client/public:/home/node/app/public
      - ./packages/client/src:/home/node/app/src
      - ./packages/client/package.json:/home/node/app/package.json
      - ./packages/client/tsconfig.json:/home/node/app/tsconfig.json
      - ./packages/client/.env:/home/node/app/.env
    ports:
      - 3000:3000
